filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.labels.analytics_source: 'true'
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

output.logstash:
  hosts: ['${LOGSTASH_HOSTS:logstash:5044}']
  ssl.enabled: ${LOGSTASH_SSL_ENABLED:false}
  ssl.certificate_authorities: ['${LOGSTASH_SSL_CA:}']

logging.level: info
