input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
  }
  date {
    match => ["@timestamp", "ISO8601"]
  }
  mutate {
    remove_field => ["message", "@version", "agent", "ecs", "host", "input", "log", "tags", "stream", "container", "docker", "event", "cloud", "orchestrator"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "events"
    manage_template => true
    template => "/usr/share/logstash/templates/events-template.json"
    template_name => "events"
    template_overwrite => true
    ilm_enabled => false
  }
}
