input {
  http {
    port => 8080
    codec => json_lines
  }
}

filter {
  date {
    match => ["@timestamp", "ISO8601"]
  }
  mutate {
    remove_field => ["@version", "event", "host", "url", "http", "user_agent", "message", "tags"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "events"
    manage_template => false
    ilm_enabled => false
  }
}
